### ISSUE TITLE
[공통] 로그인, 로그아웃 구현

### ISSUE THREAD

**Issue by JooYoung1121** [Naver-Children-StudyRoom/service-issue#1]
# 로그인, 로그아웃 구현 

- 단순 아이디 및 비밀번호에 따른 로그인과 로그아웃 구현
- 아직 회원이 가지고 있어야 하는 정보에 대해선 추가 회의가 필요하기에 회원가입 및 프로필은 다른 이슈로 진행할 예정 

### 네아로
- 네아로 쓸까요 말까요?!

**Comment by JooYoung1121** [comment]
질문이 있어서 남깁니다. 

네아로 쓸까요 말까요?! 천천히 의견 달아주세욥

**Comment by Leeseungeun1** [comment]
네아로 사용하는게 좋은 것 같은데요,
처음에는 네아로를 제외하고 구현 하고 이후에 소셜 로그인 기능을 덧붙이는 방향으로 진행하면 어떨까요?
