### ISSUE TITLE
[공통] 메인화면 구현관련 논의사항

### ISSUE THREAD

**Issue by JooYoung1121** [Naver-Children-StudyRoom/service-issue#4]
## 배경 
- 앱이랑 웹은 살짝 흐름이 다를 것 같아서 이슈 생성 
- 추가로 현재 우리가 기획했던 메인화면은 로그인 이후 화면임 -> 로그인을 하기 전엔 어떻게 보여져야 할지에 대해 논의가 필요해보임 

### 의견 
1. 우선 웹에서는 나의독서실요약, 마이플래너 요약등과 같은 화면에선 로그인이 필요합니다 와 같은 화면을 구현하면 될 것 같다. (블러처리?)
2. 또는 로그인을 안할 시 그 view?라고 해야할진 모르겠지만 숨김 처리하고 로그인이 되있을 때 보여주고 하는 식으로 하면 될 것 같기두 합니다. 
- 이렇게 될 경우 비로그인시 서비스소개 및 튜토리얼 정도가 노출될 것 같음 
3. 앱은 아싸리 처음에 Splash화면을 보여주고 로그인 버튼만 노출하는 식으로 접근하거나 2번 방식으로 구현을 진행해야 할 것 같다. 
- 첫번째 방식으로 갈 경우 Splash화면이 서비스 소개 화면이기 때문에 로그인 후 메인화면에선 서비스소개를 단순하게 갈 수 있다. 
- 두번째 방식으로 갈 경우 웹이랑 컨셉을 동일하게 갈 수 있을 것 같다. 
- 스플래시 예시 화면 
![image](https://user-images.githubusercontent.com/37646197/153695102-94ebd0f9-6b61-424f-9461-e579ba924669.png)

### 결론 
- 웹이랑 앱을 컨셉을 똑같이 가야할지 아니면 앱은 좀 별도로 가야할지 의견 부탁드립니다. 

@Leeseungeun1 @HyoSupSong @Song-Jihyun @tjdwls3469

**Comment by Leeseungeun1** [comment]
저는 2안이 더 좋은 것 같습니다.

**1안을 선택했을 경우**
* 로그인이 안 된 경우에는 splash 화면만 보여주기 때문에 구현하기가 쉽다.
* 사용 예정 사람들에게 앱을 둘러볼 수 있는 기회를 제공하지 못한다.

**2안을 선택했을 경우**
* 앱과 웹의 UX가 동일해지기 때문에 혼란이 없을 것이다.

로 생각을 정리했는데, 1안의 두번째 case가 마이너스가 되는 요소가 크다고 생각을 했습니다.

해당 이슈를 고민하다가 든 생각인데, Advanced 기능으로 비회원에게 일부 기능을 열어주는 것을 논의하는 것도 좋을 것 같습니다 ~

**Comment by JooYoung1121** [comment]
저도 2안이 더 좋은 것 같습니다~~~~ 웹과 앱 디자인가이드 비슷하게 가고 각자 구현상으로 대처하는거로 갑시당

**Comment by JooYoung1121** [comment]
논의 완료되서 이슈 종료합니다
